# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAlocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(max_length=10)),
                ('sub_id', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('timing', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FacultyOtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=30)),
                ('userid', models.CharField(blank=True, max_length=50)),
                ('cid', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainUserOtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(max_length=10)),
                ('userid', models.CharField(max_length=50)),
                ('cid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Timeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=10)),
                ('p_start_time', models.DateTimeField()),
                ('p_end_time', models.DateTimeField()),
            ],
        ),
    ]
